services:
  - type: web
    name: estuturno-backend
    env: node
    region: ohio
    plan: free
    rootDir: backend
    buildCommand: npm install && npx prisma generate && npx tsc
    startCommand: npx prisma db push && node dist/index.js
    healthCheckPath: /api/health
    envVars:
      - key: NODE_VERSION
        value: 22
      - key: CORS_ORIGINS
        value: https://estuturno-frontend.onrender.com

  - type: static_site
    name: estuturno-frontend
    region: ohio
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    rootDir: frontend
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://estuturno-backend.onrender.com
